language: android
jdk: oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.2
    - android-24
    - android-25
    - sys-img-armeabi-v7a-android-24
    - extra-android-m2repository
    - extra-android-support

before_install:
  - chmod +x gradlew

before_script:
  - echo no | android create avd --force -n test -t android-24 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window -verbose > avd.log &
  - android-wait-for-emulator
  - sleep 60
  - adb shell input keyevent 82
  #- adb logcat ActivityTestRule:I TestRunner:I LifecycleMonitor:D ActivityManager:D WTT:D WTTT:D WTTS:D *:S > logcat.log &
  - adb logcat > logcat.log &

script: ./gradlew test connectedAndroidTest --info

after_failure:
  - cat avd.log
  - cat logcat.log

